/**
 * Comprehensive emoji database organized by categories with Hebrew + English keywords.
 * Used by the EmojiPicker dialog for browsing and searching.
 */

/** Maps legacy string iconIds (e.g. 'dairy') to their emoji characters.
 *  Used by CategoryIcon for backward compatibility with existing data. */
export const LEGACY_ICON_MAP: Record<string, string> = {
  dairy: '🥛',
  bread: '🍞',
  vegetables: '🥬',
  fruits: '🍎',
  meat: '🥩',
  groceries: '🛒',
  leaf: '🌿',
  carrot: '🥕',
  eggplant: '🍆',
  tomato: '🍅',
  avocado: '🥑',
  broccoli: '🥦',
  cucumber: '🥒',
  pepper: '🫑',
  egg: '🥚',
  cheese: '🧀',
  honey: '🍯',
  beans: '🫘',
  lemon: '🍋',
  grapes: '🍇',
  banana: '🍌',
  mushroom: '🍄',
  onion: '🧅',
  corn: '🌽',
  olive: '🫒',
  salad: '🥗',
  strawberry: '🍓',
  watermelon: '🍉',
  peach: '🍑',
  cherry: '🍒',
  blueberry: '🫐',
  mango: '🥭',
  pineapple: '🍍',
  coconut: '🥥',
  garlic: '🧄',
  potato: '🥔',
  yam: '🍠',
  peanut: '🥜',
};

export interface EmojiItem {
  emoji: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'פרצופים',
    icon: '😊',
    emojis: [
      { emoji: '😀', keywords: ['שמח', 'חיוך', 'smile', 'happy'] },
      { emoji: '😃', keywords: ['שמח', 'חיוך גדול', 'grin'] },
      { emoji: '😄', keywords: ['שמח', 'צוחק', 'laugh'] },
      { emoji: '😁', keywords: ['חיוך', 'שיניים', 'grin'] },
      { emoji: '😊', keywords: ['מסמיק', 'חיוך', 'blush'] },
      { emoji: '🥰', keywords: ['אהבה', 'לבבות', 'love'] },
      { emoji: '😍', keywords: ['אהבה', 'עיניים', 'heart eyes'] },
      { emoji: '🤩', keywords: ['כוכבים', 'מתלהב', 'star'] },
      { emoji: '😎', keywords: ['מגניב', 'משקפיים', 'cool'] },
      { emoji: '🤗', keywords: ['חיבוק', 'hug'] },
      { emoji: '🤔', keywords: ['חושב', 'thinking'] },
      { emoji: '😴', keywords: ['ישן', 'עייף', 'sleep'] },
      { emoji: '🥳', keywords: ['מסיבה', 'חגיגה', 'party'] },
      { emoji: '😢', keywords: ['עצוב', 'דמעה', 'sad', 'cry'] },
      { emoji: '😭', keywords: ['בוכה', 'cry'] },
      { emoji: '😱', keywords: ['מזועזע', 'shocked'] },
      { emoji: '😇', keywords: ['מלאך', 'angel'] },
      { emoji: '🤑', keywords: ['כסף', 'money'] },
      { emoji: '😈', keywords: ['שד', 'שובב', 'devil'] },
      { emoji: '💀', keywords: ['גולגולת', 'skull'] },
      { emoji: '👻', keywords: ['רוח', 'ghost'] },
      { emoji: '🤖', keywords: ['רובוט', 'robot'] },
      { emoji: '👽', keywords: ['חייזר', 'alien'] },
      { emoji: '💩', keywords: ['קקי', 'poop'] },
      { emoji: '🤡', keywords: ['ליצן', 'clown'] },
      { emoji: '👶', keywords: ['תינוק', 'baby'] },
      { emoji: '👧', keywords: ['ילדה', 'girl'] },
      { emoji: '👦', keywords: ['ילד', 'boy'] },
      { emoji: '👩', keywords: ['אישה', 'woman'] },
      { emoji: '👨', keywords: ['גבר', 'man'] },
      { emoji: '👴', keywords: ['סבא', 'זקן', 'old man'] },
      { emoji: '👵', keywords: ['סבתא', 'old woman'] },
      { emoji: '🧑‍🍳', keywords: ['שף', 'טבח', 'cook', 'chef'] },
      { emoji: '👋', keywords: ['שלום', 'יד', 'wave', 'hello'] },
      { emoji: '👍', keywords: ['לייק', 'אישור', 'thumbs up'] },
      { emoji: '👎', keywords: ['לא אהבתי', 'thumbs down'] },
      { emoji: '👏', keywords: ['מחיאות כפיים', 'clap'] },
      { emoji: '🙏', keywords: ['תודה', 'בקשה', 'pray', 'thanks'] },
      { emoji: '💪', keywords: ['שריר', 'חזק', 'muscle', 'strong'] },
    ],
  },
  {
    id: 'food',
    label: 'אוכל ושתייה',
    icon: '🍔',
    emojis: [
      // Fruits
      { emoji: '🍎', keywords: ['תפוח', 'פרי', 'פירות', 'apple', 'fruit'] },
      { emoji: '🍐', keywords: ['אגס', 'pear'] },
      { emoji: '🍊', keywords: ['תפוז', 'orange'] },
      { emoji: '🍋', keywords: ['לימון', 'lemon'] },
      { emoji: '🍌', keywords: ['בננה', 'banana'] },
      { emoji: '🍉', keywords: ['אבטיח', 'watermelon'] },
      { emoji: '🍇', keywords: ['ענבים', 'grapes'] },
      { emoji: '🍓', keywords: ['תות', 'strawberry'] },
      { emoji: '🫐', keywords: ['אוכמניות', 'blueberry'] },
      { emoji: '🍒', keywords: ['דובדבן', 'cherry'] },
      { emoji: '🍑', keywords: ['אפרסק', 'peach'] },
      { emoji: '🥭', keywords: ['מנגו', 'mango'] },
      { emoji: '🍍', keywords: ['אננס', 'pineapple'] },
      { emoji: '🥥', keywords: ['קוקוס', 'coconut'] },
      { emoji: '🥝', keywords: ['קיווי', 'kiwi'] },
      // Vegetables
      { emoji: '🍅', keywords: ['עגבניה', 'tomato'] },
      { emoji: '🍆', keywords: ['חציל', 'eggplant'] },
      { emoji: '🥑', keywords: ['אבוקדו', 'avocado'] },
      { emoji: '🥔', keywords: ['תפוח אדמה', 'potato'] },
      { emoji: '🥕', keywords: ['גזר', 'carrot'] },
      { emoji: '🌽', keywords: ['תירס', 'corn'] },
      { emoji: '🌶️', keywords: ['צילי', 'פלפל חריף', 'chili', 'hot pepper'] },
      { emoji: '🫑', keywords: ['פלפל', 'pepper'] },
      { emoji: '🥒', keywords: ['מלפפון', 'cucumber'] },
      { emoji: '🥬', keywords: ['ירקות', 'חסה', 'ירק עלים', 'lettuce', 'greens'] },
      { emoji: '🥦', keywords: ['ברוקולי', 'broccoli'] },
      { emoji: '🧄', keywords: ['שום', 'garlic'] },
      { emoji: '🧅', keywords: ['בצל', 'onion'] },
      { emoji: '🍄', keywords: ['פטריות', 'mushroom'] },
      { emoji: '🫒', keywords: ['זיתים', 'olive'] },
      { emoji: '🍠', keywords: ['בטטה', 'yam', 'sweet potato'] },
      // Proteins & Dairy
      { emoji: '🥩', keywords: ['בשר', 'סטייק', 'meat', 'steak'] },
      { emoji: '🍗', keywords: ['עוף', 'שוקיים', 'chicken', 'leg'] },
      { emoji: '🍖', keywords: ['בשר', 'צלע', 'meat', 'bone'] },
      { emoji: '🥚', keywords: ['ביצה', 'egg'] },
      { emoji: '🧀', keywords: ['גבינה', 'cheese'] },
      { emoji: '🥛', keywords: ['חלב', 'milk', 'dairy'] },
      { emoji: '🐟', keywords: ['דג', 'fish'] },
      { emoji: '🍤', keywords: ['שרימפס', 'shrimp'] },
      // Bread & Grains
      { emoji: '🍞', keywords: ['לחם', 'bread'] },
      { emoji: '🥐', keywords: ['קרואסון', 'croissant'] },
      { emoji: '🥖', keywords: ['באגט', 'baguette'] },
      { emoji: '🥨', keywords: ['בייגלה', 'pretzel'] },
      { emoji: '🥯', keywords: ['בייגל', 'bagel'] },
      { emoji: '🧇', keywords: ['וופל', 'waffle'] },
      { emoji: '🥞', keywords: ['פנקייק', 'pancake'] },
      { emoji: '🍳', keywords: ['ביצת עין', 'חביתה', 'fried egg'] },
      // Prepared food
      { emoji: '🌭', keywords: ['נקניקייה', 'hot dog'] },
      { emoji: '🍔', keywords: ['המבורגר', 'burger'] },
      { emoji: '🍟', keywords: ['צ\'יפס', 'תפוחי אדמה', 'fries'] },
      { emoji: '🍕', keywords: ['פיצה', 'pizza'] },
      { emoji: '🌮', keywords: ['טאקו', 'taco'] },
      { emoji: '🌯', keywords: ['בוריטו', 'שווארמה', 'wrap', 'burrito'] },
      { emoji: '🥙', keywords: ['פיתה', 'פלאפל', 'pita', 'falafel'] },
      { emoji: '🧆', keywords: ['פלאפל', 'falafel'] },
      { emoji: '🥗', keywords: ['סלט', 'salad'] },
      { emoji: '🍝', keywords: ['פסטה', 'ספגטי', 'pasta', 'spaghetti'] },
      { emoji: '🍜', keywords: ['נודלס', 'מרק', 'noodles', 'ramen'] },
      { emoji: '🍲', keywords: ['תבשיל', 'מרק', 'stew', 'soup'] },
      { emoji: '🍛', keywords: ['קארי', 'curry'] },
      { emoji: '🍣', keywords: ['סושי', 'sushi'] },
      { emoji: '🍱', keywords: ['בנטו', 'bento'] },
      { emoji: '🥟', keywords: ['כיסונים', 'דאמפלינג', 'dumpling'] },
      // Snacks & Sweets
      { emoji: '🍿', keywords: ['פופקורן', 'popcorn'] },
      { emoji: '🍩', keywords: ['דונאט', 'סופגניה', 'donut'] },
      { emoji: '🍪', keywords: ['עוגייה', 'cookie'] },
      { emoji: '🎂', keywords: ['עוגה', 'יום הולדת', 'cake', 'birthday'] },
      { emoji: '🍰', keywords: ['עוגה', 'cake', 'slice'] },
      { emoji: '🧁', keywords: ['קאפקייק', 'cupcake'] },
      { emoji: '🍭', keywords: ['סוכרייה', 'lollipop', 'candy'] },
      { emoji: '🍬', keywords: ['סוכריה', 'ממתק', 'candy', 'sweet'] },
      { emoji: '🍫', keywords: ['שוקולד', 'chocolate'] },
      { emoji: '🍯', keywords: ['דבש', 'honey'] },
      { emoji: '🥜', keywords: ['בוטנים', 'peanut'] },
      { emoji: '🫘', keywords: ['קטניות', 'שעועית', 'beans'] },
      { emoji: '🌰', keywords: ['ערמון', 'chestnut', 'nut'] },
      // Drinks
      { emoji: '☕', keywords: ['קפה', 'coffee'] },
      { emoji: '🍵', keywords: ['תה', 'tea'] },
      { emoji: '🧃', keywords: ['מיץ', 'juice', 'box'] },
      { emoji: '🥤', keywords: ['שתייה', 'כוס', 'drink', 'cup'] },
      { emoji: '🧋', keywords: ['באבל טי', 'bubble tea'] },
      { emoji: '🍺', keywords: ['בירה', 'beer'] },
      { emoji: '🍷', keywords: ['יין', 'wine'] },
      { emoji: '🍾', keywords: ['שמפניה', 'champagne'] },
      { emoji: '🥂', keywords: ['לחיים', 'cheers'] },
      // Other grocery
      { emoji: '🛒', keywords: ['עגלה', 'קניות', 'מכולת', 'cart', 'groceries'] },
      { emoji: '🧈', keywords: ['חמאה', 'butter'] },
      { emoji: '🫙', keywords: ['צנצנת', 'jar'] },
      { emoji: '🧂', keywords: ['מלח', 'salt'] },
      { emoji: '🫗', keywords: ['שפיכה', 'pour'] },
      { emoji: '🥫', keywords: ['שימורים', 'can', 'canned'] },
      { emoji: '🍚', keywords: ['אורז', 'rice'] },
    ],
  },
  {
    id: 'animals',
    label: 'חיות וטבע',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', keywords: ['כלב', 'dog'] },
      { emoji: '🐱', keywords: ['חתול', 'cat'] },
      { emoji: '🐭', keywords: ['עכבר', 'mouse'] },
      { emoji: '🐹', keywords: ['אוגר', 'hamster'] },
      { emoji: '🐰', keywords: ['ארנב', 'rabbit'] },
      { emoji: '🦊', keywords: ['שועל', 'fox'] },
      { emoji: '🐻', keywords: ['דוב', 'bear'] },
      { emoji: '🐼', keywords: ['פנדה', 'panda'] },
      { emoji: '🐨', keywords: ['קואלה', 'koala'] },
      { emoji: '🐯', keywords: ['נמר', 'tiger'] },
      { emoji: '🦁', keywords: ['אריה', 'lion'] },
      { emoji: '🐮', keywords: ['פרה', 'cow'] },
      { emoji: '🐷', keywords: ['חזיר', 'pig'] },
      { emoji: '🐸', keywords: ['צפרדע', 'frog'] },
      { emoji: '🐵', keywords: ['קוף', 'monkey'] },
      { emoji: '🐔', keywords: ['תרנגולת', 'chicken'] },
      { emoji: '🐧', keywords: ['פינגווין', 'penguin'] },
      { emoji: '🐦', keywords: ['ציפור', 'bird'] },
      { emoji: '🦅', keywords: ['נשר', 'eagle'] },
      { emoji: '🦉', keywords: ['ינשוף', 'owl'] },
      { emoji: '🐝', keywords: ['דבורה', 'bee'] },
      { emoji: '🦋', keywords: ['פרפר', 'butterfly'] },
      { emoji: '🐢', keywords: ['צב', 'turtle'] },
      { emoji: '🐠', keywords: ['דג', 'fish'] },
      { emoji: '🐬', keywords: ['דולפין', 'dolphin'] },
      { emoji: '🐳', keywords: ['לוויתן', 'whale'] },
      { emoji: '🦀', keywords: ['סרטן', 'crab'] },
      { emoji: '🐙', keywords: ['תמנון', 'octopus'] },
      { emoji: '🐌', keywords: ['חילזון', 'snail'] },
      { emoji: '🦜', keywords: ['תוכי', 'parrot'] },
      { emoji: '🐿️', keywords: ['סנאי', 'squirrel'] },
      { emoji: '🦔', keywords: ['קיפוד', 'hedgehog'] },
      // Nature
      { emoji: '🌸', keywords: ['פרח', 'דובדבן', 'blossom', 'flower'] },
      { emoji: '🌺', keywords: ['פרח', 'hibiscus'] },
      { emoji: '🌻', keywords: ['חמנייה', 'sunflower'] },
      { emoji: '🌹', keywords: ['ורד', 'rose'] },
      { emoji: '🌷', keywords: ['צבעוני', 'tulip'] },
      { emoji: '🌵', keywords: ['קקטוס', 'cactus'] },
      { emoji: '🌴', keywords: ['דקל', 'palm'] },
      { emoji: '🌲', keywords: ['עץ', 'tree', 'pine'] },
      { emoji: '🌿', keywords: ['עלים', 'עשב', 'herb', 'leaf'] },
      { emoji: '☘️', keywords: ['תלתן', 'clover'] },
      { emoji: '🍀', keywords: ['מזל', 'תלתן', 'luck', 'clover'] },
      { emoji: '🍁', keywords: ['עלה', 'סתיו', 'maple', 'fall'] },
      { emoji: '🌾', keywords: ['חיטה', 'שיבולת', 'wheat'] },
      { emoji: '🌊', keywords: ['גל', 'ים', 'wave', 'ocean'] },
      { emoji: '🌈', keywords: ['קשת', 'rainbow'] },
      { emoji: '☀️', keywords: ['שמש', 'sun'] },
      { emoji: '🌙', keywords: ['ירח', 'moon'] },
      { emoji: '⭐', keywords: ['כוכב', 'star'] },
    ],
  },
  {
    id: 'activities',
    label: 'ספורט ופעילויות',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', keywords: ['כדורגל', 'soccer', 'football'] },
      { emoji: '🏀', keywords: ['כדורסל', 'basketball'] },
      { emoji: '🏈', keywords: ['פוטבול', 'football'] },
      { emoji: '⚾', keywords: ['בייסבול', 'baseball'] },
      { emoji: '🎾', keywords: ['טניס', 'tennis'] },
      { emoji: '🏐', keywords: ['כדורעף', 'volleyball'] },
      { emoji: '🏓', keywords: ['פינג פונג', 'ping pong'] },
      { emoji: '🏸', keywords: ['בדמינטון', 'badminton'] },
      { emoji: '🎱', keywords: ['ביליארד', 'pool'] },
      { emoji: '🏋️', keywords: ['הרמת משקולות', 'gym', 'weights'] },
      { emoji: '🧘', keywords: ['יוגה', 'yoga'] },
      { emoji: '🏊', keywords: ['שחייה', 'swim'] },
      { emoji: '🚴', keywords: ['אופניים', 'cycling', 'bike'] },
      { emoji: '🏃', keywords: ['ריצה', 'run'] },
      { emoji: '🎮', keywords: ['משחק', 'גיימינג', 'game', 'gaming'] },
      { emoji: '🎲', keywords: ['קוביה', 'משחק', 'dice', 'game'] },
      { emoji: '🎭', keywords: ['תיאטרון', 'theater'] },
      { emoji: '🎨', keywords: ['אמנות', 'ציור', 'art', 'paint'] },
      { emoji: '🎬', keywords: ['סרט', 'קולנוע', 'movie', 'film'] },
      { emoji: '🎤', keywords: ['מיקרופון', 'שירה', 'microphone', 'sing'] },
      { emoji: '🎧', keywords: ['אוזניות', 'מוזיקה', 'headphones', 'music'] },
      { emoji: '🎼', keywords: ['מוזיקה', 'תווים', 'music'] },
      { emoji: '🎹', keywords: ['פסנתר', 'piano'] },
      { emoji: '🎸', keywords: ['גיטרה', 'guitar'] },
      { emoji: '🎯', keywords: ['מטרה', 'target', 'dart'] },
      { emoji: '🎳', keywords: ['באולינג', 'bowling'] },
      { emoji: '🎪', keywords: ['קרקס', 'circus'] },
      { emoji: '🏆', keywords: ['גביע', 'ניצחון', 'trophy', 'win'] },
      { emoji: '🥇', keywords: ['מדליה', 'זהב', 'gold', 'medal'] },
      { emoji: '🎉', keywords: ['מסיבה', 'חגיגה', 'party'] },
      { emoji: '🎈', keywords: ['בלון', 'balloon'] },
      { emoji: '🎁', keywords: ['מתנה', 'gift', 'present'] },
    ],
  },
  {
    id: 'travel',
    label: 'נסיעות ומקומות',
    icon: '🚗',
    emojis: [
      { emoji: '🚗', keywords: ['מכונית', 'רכב', 'car'] },
      { emoji: '🚕', keywords: ['מונית', 'taxi'] },
      { emoji: '🚌', keywords: ['אוטובוס', 'bus'] },
      { emoji: '🚎', keywords: ['אוטובוס', 'trolley'] },
      { emoji: '🏎️', keywords: ['מירוצים', 'racing'] },
      { emoji: '🚓', keywords: ['משטרה', 'police'] },
      { emoji: '🚑', keywords: ['אמבולנס', 'ambulance'] },
      { emoji: '🚒', keywords: ['כיבוי אש', 'fire truck'] },
      { emoji: '🛻', keywords: ['טנדר', 'pickup', 'truck'] },
      { emoji: '🚚', keywords: ['משאית', 'truck'] },
      { emoji: '🚜', keywords: ['טרקטור', 'tractor'] },
      { emoji: '🏍️', keywords: ['אופנוע', 'motorcycle'] },
      { emoji: '🛵', keywords: ['קטנוע', 'scooter'] },
      { emoji: '🚲', keywords: ['אופניים', 'bicycle'] },
      { emoji: '🚂', keywords: ['רכבת', 'train'] },
      { emoji: '✈️', keywords: ['מטוס', 'טיסה', 'airplane', 'flight'] },
      { emoji: '🚀', keywords: ['טיל', 'חלל', 'rocket', 'space'] },
      { emoji: '🚁', keywords: ['מסוק', 'helicopter'] },
      { emoji: '⛵', keywords: ['סירה', 'מפרשית', 'sailboat'] },
      { emoji: '🚤', keywords: ['סירה', 'boat'] },
      { emoji: '🏠', keywords: ['בית', 'house', 'home'] },
      { emoji: '🏡', keywords: ['בית', 'גינה', 'garden', 'house'] },
      { emoji: '🏢', keywords: ['בניין', 'משרד', 'office', 'building'] },
      { emoji: '🏥', keywords: ['בית חולים', 'hospital'] },
      { emoji: '🏦', keywords: ['בנק', 'bank'] },
      { emoji: '🏪', keywords: ['חנות', 'store', 'shop'] },
      { emoji: '🏫', keywords: ['בית ספר', 'school'] },
      { emoji: '🏰', keywords: ['טירה', 'castle'] },
      { emoji: '🗼', keywords: ['מגדל', 'tower'] },
      { emoji: '🏖️', keywords: ['חוף', 'ים', 'beach'] },
      { emoji: '🏔️', keywords: ['הר', 'mountain'] },
      { emoji: '⛺', keywords: ['אוהל', 'קמפינג', 'tent', 'camping'] },
    ],
  },
  {
    id: 'objects',
    label: 'חפצים',
    icon: '💡',
    emojis: [
      { emoji: '📱', keywords: ['טלפון', 'פלאפון', 'phone', 'mobile'] },
      { emoji: '💻', keywords: ['מחשב', 'לפטופ', 'computer', 'laptop'] },
      { emoji: '⌨️', keywords: ['מקלדת', 'keyboard'] },
      { emoji: '🖥️', keywords: ['מחשב', 'מסך', 'desktop'] },
      { emoji: '📷', keywords: ['מצלמה', 'camera'] },
      { emoji: '📺', keywords: ['טלוויזיה', 'tv'] },
      { emoji: '📻', keywords: ['רדיו', 'radio'] },
      { emoji: '🔔', keywords: ['פעמון', 'bell'] },
      { emoji: '💡', keywords: ['נורה', 'רעיון', 'bulb', 'idea', 'light'] },
      { emoji: '🔦', keywords: ['פנס', 'flashlight'] },
      { emoji: '🕯️', keywords: ['נר', 'candle'] },
      { emoji: '📦', keywords: ['קופסה', 'חבילה', 'box', 'package'] },
      { emoji: '🧰', keywords: ['ארגז כלים', 'toolbox'] },
      { emoji: '🔧', keywords: ['מפתח ברגים', 'wrench'] },
      { emoji: '🔨', keywords: ['פטיש', 'hammer'] },
      { emoji: '⚙️', keywords: ['גלגל שיניים', 'הגדרות', 'gear', 'settings'] },
      { emoji: '💰', keywords: ['כסף', 'שק', 'money', 'bag'] },
      { emoji: '💳', keywords: ['כרטיס', 'אשראי', 'credit card'] },
      { emoji: '🏷️', keywords: ['תגית', 'מחיר', 'tag', 'label'] },
      { emoji: '📌', keywords: ['נעץ', 'סיכה', 'pin'] },
      { emoji: '📎', keywords: ['מהדק', 'clip'] },
      { emoji: '✂️', keywords: ['מספריים', 'scissors'] },
      { emoji: '📝', keywords: ['פתק', 'כתיבה', 'memo', 'note', 'write'] },
      { emoji: '📚', keywords: ['ספרים', 'books'] },
      { emoji: '📖', keywords: ['ספר', 'book'] },
      { emoji: '🔑', keywords: ['מפתח', 'key'] },
      { emoji: '🔐', keywords: ['מנעול', 'lock'] },
      { emoji: '💊', keywords: ['כדור', 'תרופה', 'pill', 'medicine'] },
      { emoji: '🩹', keywords: ['פלסתר', 'bandage'] },
      { emoji: '🧹', keywords: ['מטאטא', 'broom', 'clean'] },
      { emoji: '🧽', keywords: ['ספוג', 'sponge'] },
      { emoji: '🪣', keywords: ['דלי', 'bucket'] },
      { emoji: '🧴', keywords: ['סבון', 'קרם', 'lotion', 'soap'] },
      { emoji: '🪥', keywords: ['מברשת שיניים', 'toothbrush'] },
      { emoji: '🧻', keywords: ['נייר טואלט', 'toilet paper'] },
      { emoji: '👕', keywords: ['חולצה', 'shirt'] },
      { emoji: '👖', keywords: ['מכנסיים', 'pants', 'jeans'] },
      { emoji: '👟', keywords: ['נעליים', 'shoes', 'sneaker'] },
      { emoji: '👜', keywords: ['תיק', 'bag', 'purse'] },
      { emoji: '🎒', keywords: ['תרמיל', 'ילקוט', 'backpack'] },
      { emoji: '👶', keywords: ['תינוק', 'baby'] },
      { emoji: '🧸', keywords: ['דובי', 'צעצוע', 'teddy bear', 'toy'] },
    ],
  },
  {
    id: 'symbols',
    label: 'סמלים',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', keywords: ['לב', 'אהבה', 'heart', 'love'] },
      { emoji: '🧡', keywords: ['לב כתום', 'orange heart'] },
      { emoji: '💛', keywords: ['לב צהוב', 'yellow heart'] },
      { emoji: '💚', keywords: ['לב ירוק', 'green heart'] },
      { emoji: '💙', keywords: ['לב כחול', 'blue heart'] },
      { emoji: '💜', keywords: ['לב סגול', 'purple heart'] },
      { emoji: '🖤', keywords: ['לב שחור', 'black heart'] },
      { emoji: '🤍', keywords: ['לב לבן', 'white heart'] },
      { emoji: '❗', keywords: ['קריאה', 'exclamation'] },
      { emoji: '❓', keywords: ['שאלה', 'question'] },
      { emoji: '✅', keywords: ['וי', 'אישור', 'check', 'done'] },
      { emoji: '❌', keywords: ['איקס', 'ביטול', 'x', 'cancel'] },
      { emoji: '⭕', keywords: ['עיגול', 'circle'] },
      { emoji: '🔴', keywords: ['אדום', 'red'] },
      { emoji: '🔵', keywords: ['כחול', 'blue'] },
      { emoji: '🟢', keywords: ['ירוק', 'green'] },
      { emoji: '🟡', keywords: ['צהוב', 'yellow'] },
      { emoji: '🟠', keywords: ['כתום', 'orange'] },
      { emoji: '🟣', keywords: ['סגול', 'purple'] },
      { emoji: '⚡', keywords: ['ברק', 'lightning', 'electric'] },
      { emoji: '✨', keywords: ['ניצוצות', 'sparkles'] },
      { emoji: '💫', keywords: ['כוכב', 'dizzy'] },
      { emoji: '🌟', keywords: ['כוכב זוהר', 'glowing star'] },
      { emoji: '🔥', keywords: ['אש', 'fire', 'hot'] },
      { emoji: '💧', keywords: ['טיפה', 'מים', 'water', 'drop'] },
      { emoji: '💨', keywords: ['רוח', 'wind'] },
      { emoji: '🎵', keywords: ['מוזיקה', 'תווים', 'music', 'note'] },
      { emoji: '💤', keywords: ['שינה', 'sleep'] },
      { emoji: '♻️', keywords: ['מיחזור', 'recycle'] },
      { emoji: '🔒', keywords: ['נעול', 'locked'] },
      { emoji: '🔓', keywords: ['פתוח', 'unlocked'] },
      { emoji: '⚠️', keywords: ['אזהרה', 'warning'] },
      { emoji: '🚫', keywords: ['אסור', 'prohibited'] },
      { emoji: '💯', keywords: ['מאה', 'מושלם', 'hundred', 'perfect'] },
      { emoji: '🆕', keywords: ['חדש', 'new'] },
      { emoji: '🆓', keywords: ['חינם', 'free'] },
      { emoji: '🔝', keywords: ['למעלה', 'top'] },
      { emoji: '➡️', keywords: ['חץ', 'ימין', 'arrow', 'right'] },
      { emoji: '⬅️', keywords: ['חץ', 'שמאל', 'arrow', 'left'] },
    ],
  },
];
